---
name: Texinfo-Menus
version: 1.00
author:
  - Christopher J. Madsen <cjm@pobox.com>
abstract: Update node links and menus in Texinfo documents
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Test::More: 0
  perl: 5.6.0
build_requires:
  FindBin: 0
  Module::Build: 0
dynamic_config: 1
provides:
  Texinfo::Menus:
    file: lib/Texinfo/Menus.pm
    version: 1.00
generated_by: Module::Build version 0.28
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
