---
name: Texinfo-Menus
version: 1.01
author:
  - 'Christopher J. Madsen <perl@cjmweb.net>'
abstract: Update node links and menus in Texinfo documents
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  perl: 5.6.0
build_requires:
  FindBin: 0
  Module::Build: 0
  Test::More: 0
dynamic_config: 1
provides:
  Texinfo::Menus:
    file: lib/Texinfo/Menus.pm
    version: 1.01
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
no_index:
  file:
    - My_Build.pm
